/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_rafaelajuria2;

import java.io.IOException;
import java.util.ArrayList;

/**
 * 
 * @author rajur
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    //CRUDs
        //Alumnos
            //Create
    public static void AgregarAlumno(int edad, int ID, String Carrera, int AñoEnCurso, double Promedio, String Facultad, String Nombre, String Apellido, int NumeroDeRegistro, String Username, String Password) throws IOException
    {
       AdministradorAlumnos Admin= new AdministradorAlumnos("./alumnos.txt");        
        Admin.LoadFile();
        Alumno Temporal = new Alumno(edad,ID,Carrera,AñoEnCurso,Promedio,Facultad,Nombre,Apellido,NumeroDeRegistro,Username,Password);
        Admin.getAlumnosGuardados().add(Temporal);        
        Admin.WriteFile(); 
    }
            //Read
    public static ArrayList<Alumno> LeerAlumnos()
    {
       ArrayList<Alumno> output;
       AdministradorAlumnos Admin= new AdministradorAlumnos("./alumnos.txt");        
       Admin.LoadFile(); 
       output=Admin.getAlumnosGuardados();
       return output;
    }
            //Update
    public static void ActualizarAlumnos(int Position,int edad, int ID, String Carrera, int AñoEnCurso, double Promedio, String Facultad, String Nombre, String Apellido, int NumeroDeRegistro, String Username, String Password) throws IOException
    {
      AdministradorAlumnos Admin= new AdministradorAlumnos("./alumnos.txt");        
      Admin.LoadFile();
      Admin.getAlumnosGuardados().get(Position).setEdad(edad);
      Admin.getAlumnosGuardados().get(Position).setID(ID);
      Admin.getAlumnosGuardados().get(Position).setCarrera(Carrera);
      Admin.getAlumnosGuardados().get(Position).setAñoEnCurso(AñoEnCurso);
      Admin.getAlumnosGuardados().get(Position).setPromedio(Promedio);
      Admin.getAlumnosGuardados().get(Position).setFacultad(Facultad);
      Admin.getAlumnosGuardados().get(Position).setNombre(Nombre);
      Admin.getAlumnosGuardados().get(Position).setApellido(Apellido);
      Admin.getAlumnosGuardados().get(Position).setNumeroDeRegistro(NumeroDeRegistro);
      Admin.getAlumnosGuardados().get(Position).setUsername(Username);
      Admin.getAlumnosGuardados().get(Position).setPassword(Password);
      Admin.WriteFile();
    }
            //Delete
    public static void BorrarAlumno(int Position) throws IOException
    {
      AdministradorAlumnos Admin= new AdministradorAlumnos("./alumnos.txt");        
      Admin.LoadFile();
      Admin.getAlumnosGuardados().remove(Position);
      Admin.WriteFile();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
